"""Initial migration: create all tables

Revision ID: 747fe4469fbc
Revises: 
Create Date: 2026-05-05 18:05:55.388005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747fe4469fbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nom', sa.String(length=100), nullable=False),
        sa.Column('prenom', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=200), nullable=False),
        sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Enum('user', 'moderateur', 'admin', name='userrole'), nullable=True),
        sa.Column('est_actif', sa.Boolean(), nullable=True),
        sa.Column('avatar_url', sa.String(length=500), nullable=True),
        sa.Column('bio', sa.String(length=500), nullable=True),
        sa.Column('type_handicap', sa.String(length=200), nullable=True),
        sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    # Create posts table
    op.create_table('posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titre', sa.String(length=300), nullable=False),
        sa.Column('contenu', sa.Text(), nullable=False),
        sa.Column('est_publie', sa.Boolean(), nullable=True),
        sa.Column('vues', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)

    # Create commentaires table
    op.create_table('commentaires',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contenu', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commentaires_id'), 'commentaires', ['id'], unique=False)

    # Create podcasts table
    op.create_table('podcasts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titre', sa.String(length=300), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('audio_url', sa.String(length=500), nullable=False),
        sa.Column('couverture_url', sa.String(length=500), nullable=True),
        sa.Column('duree_secondes', sa.Integer(), nullable=True),
        sa.Column('est_publie', sa.Boolean(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcasts_id'), 'podcasts', ['id'], unique=False)

    # Create temoignages table
    op.create_table('temoignages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titre', sa.String(length=300), nullable=False),
        sa.Column('contenu', sa.Text(), nullable=False),
        sa.Column('photo_url', sa.String(length=500), nullable=True),
        sa.Column('est_publie', sa.Boolean(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temoignages_id'), 'temoignages', ['id'], unique=False)

    # Create jobs table
    op.create_table('jobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titre', sa.String(length=300), nullable=False),
        sa.Column('entreprise', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('lieu', sa.String(length=200), nullable=True),
        sa.Column('type_contrat', sa.String(length=100), nullable=True),
        sa.Column('est_actif', sa.Boolean(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('expire_le', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)

    # Create experts table
    op.create_table('experts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nom', sa.String(length=200), nullable=False),
        sa.Column('specialite', sa.String(length=200), nullable=False),
        sa.Column('organisation', sa.String(length=200), nullable=True),
        sa.Column('email', sa.String(length=200), nullable=True),
        sa.Column('telephone', sa.String(length=50), nullable=True),
        sa.Column('ville', sa.String(length=100), nullable=True),
        sa.Column('photo_url', sa.String(length=500), nullable=True),
        sa.Column('est_actif', sa.Boolean(), nullable=True),
        sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_id'), 'experts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experts_id'), table_name='experts')
    op.drop_table('experts')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_temoignages_id'), table_name='temoignages')
    op.drop_table('temoignages')
    op.drop_index(op.f('ix_podcasts_id'), table_name='podcasts')
    op.drop_table('podcasts')
    op.drop_index(op.f('ix_commentaires_id'), table_name='commentaires')
    op.drop_table('commentaires')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
