"""add_user_certification_fields

Revision ID: b03bf652639a
Revises: d4e5f6a7b8c9
Create Date: 2026-07-05 21:03:57.139376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b03bf652639a'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signalements_cible', table_name='signalements')
    op.drop_index('ix_signalements_id', table_name='signalements')
    op.drop_table('signalements')
    op.create_index(op.f('ix_commentaires_post_id'), 'commentaires', ['post_id'], unique=False)
    op.drop_constraint('commentaires_post_id_fkey', 'commentaires', type_='foreignkey')
    op.create_foreign_key(None, 'commentaires', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'statut',
               existing_type=postgresql.ENUM('brouillon', 'en_attente', 'approuve', 'refuse', name='poststatut'),
               nullable=True,
               existing_server_default=sa.text("'en_attente'::poststatut"))
    op.add_column('users', sa.Column('document_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('document_soumis_le', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'specialite')
    op.drop_column('users', 'secteur_activite')
    op.drop_column('users', 'site_web')
    op.drop_column('users', 'nom_organisation')
    op.drop_column('users', 'est_expert_verifie')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('est_expert_verifie', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nom_organisation', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('site_web', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('secteur_activite', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('specialite', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('users', 'document_soumis_le')
    op.drop_column('users', 'document_type')
    op.drop_column('users', 'document_verified')
    op.alter_column('posts', 'statut',
               existing_type=postgresql.ENUM('brouillon', 'en_attente', 'approuve', 'refuse', name='poststatut'),
               nullable=False,
               existing_server_default=sa.text("'en_attente'::poststatut"))
    op.drop_constraint(None, 'commentaires', type_='foreignkey')
    op.create_foreign_key('commentaires_post_id_fkey', 'commentaires', 'posts', ['post_id'], ['id'])
    op.drop_index(op.f('ix_commentaires_post_id'), table_name='commentaires')
    op.create_table('signalements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cible_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cible_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raison', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('est_traite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='signalements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='signalements_pkey')
    )
    op.create_index('ix_signalements_id', 'signalements', ['id'], unique=False)
    op.create_index('ix_signalements_cible', 'signalements', ['cible_type', 'cible_id'], unique=False)
    # ### end Alembic commands ###
